"""converted datetimes from string to datetime

Revision ID: 1349ab971d6a
Revises: 5607fba81aa8
Create Date: 2024-08-12 10:45:32.534363

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1349ab971d6a'
down_revision = '5607fba81aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tg_bot_inquiries', 'created_at',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('tg_bot_inquiries', 'updated_at',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('tg_bot_inquiries', 'replied_at',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('tg_bot_users', 'created_at',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tg_bot_users', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('tg_bot_inquiries', 'replied_at',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('tg_bot_inquiries', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('tg_bot_inquiries', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
