"""Added user and inquiry tables

Revision ID: 2040e7fae3b2
Revises: 
Create Date: 2024-08-10 21:24:46.292387

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2040e7fae3b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_bot_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='gendertype'), nullable=True),
    sa.Column('disability_type', sa.Enum('none', 'first_degree', 'second_degree', 'third_degree', 'forth_degree', name='disabilitytype'), nullable=True),
    sa.Column('disability_state', sa.Enum('physical', 'mental', 'vision', 'hearing', 'psychological', 'parent', 'other', 'aids', name='disabilitystate'), nullable=True),
    sa.Column('region', sa.Enum('R0', 'R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'R8', 'R9', 'R10', 'R11', 'R12', 'R13', name='region'), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tg_bot_inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('private_question_id', sa.Integer(), nullable=False),
    sa.Column('group_question_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('bot_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('active', 'replied', 'closed', 'cancelled', name='inquirystatus'), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('group_answer_id', sa.Integer(), nullable=True),
    sa.Column('responder_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('replied_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tg_bot_users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tg_bot_inquiries')
    op.drop_table('tg_bot_users')
    # ### end Alembic commands ###
