"""Added media type to inquiry

Revision ID: 5607fba81aa8
Revises: bacc66830e3a
Create Date: 2024-08-12 04:16:06.736758

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5607fba81aa8'
down_revision = 'bacc66830e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_bot_inquiries', sa.Column('question_media_type', sa.Enum('text', 'voice', name='inquirymediatype'), nullable=False))
    op.add_column('tg_bot_inquiries', sa.Column('question_media', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_bot_inquiries', 'question_media')
    op.drop_column('tg_bot_inquiries', 'question_media_type')
    # ### end Alembic commands ###
