"""added phone and birth year to user

Revision ID: 7b4c0ff52a00
Revises: fcd9da75e18a
Create Date: 2024-08-16 16:39:01.646421

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b4c0ff52a00'
down_revision = 'fcd9da75e18a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_bot_users', sa.Column('birth_year', sa.Integer(), nullable=True))
    op.add_column('tg_bot_users', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('tg_bot_users', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_bot_users', sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('tg_bot_users', 'phone')
    op.drop_column('tg_bot_users', 'birth_year')
    # ### end Alembic commands ###
