"""Updating inquiry chat to support string

Revision ID: bacc66830e3a
Revises: 5a9e99b5bb0c
Create Date: 2024-08-12 01:19:31.774139

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bacc66830e3a'
down_revision = '5a9e99b5bb0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tg_bot_inquiries', 'group_id',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tg_bot_inquiries', 'group_id',
               existing_type=sa.VARCHAR(length=255),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)
    # ### end Alembic commands ###
